"""Focused views over the core graph and review adapters.

These protocols preserve the existing storage contracts while letting services
declare only their required operations. They do not wrap an adapter or grant
authority: tenant-scoped reads filter in storage, and callers must validate the
tenant of records fetched by globally unique ID before exposing or changing them.
No view admits free-form queries, model operations or compiler scheduling.
"""
from datetime import datetime
from typing import Protocol, runtime_checkable

from oms.domain.models import (
    Artefact, ContentBlock, Edge, Example, Publication, PublishBlock,
    QuarantinedPayload, Rule, RulePage, RulePlacement, Section, Skill,
    SkillVersion, SkillChange, Transaction, UsageEvent,
)
from oms.domain.types import RuleStatus
from oms.ports.review_queue import ReviewQueue


@runtime_checkable
class TransactionRepository(Protocol):
    """Contribution records and safe quarantine metadata, never raw payloads."""
    def upsert_transaction(self, transaction: Transaction) -> None: ...
    def get_transaction(self, transaction_id: str) -> Transaction | None: ...
    def workflow_state_for(self, transaction_id: str) -> str: ...
    def transactions_for_tenant(self, tenant_id: str, since: datetime | None = None,
                                limit: int = 200) -> list[Transaction]:
        """Newest first, filtered by tenant and time before applying the limit."""
        ...
    def record_quarantine(self, item: QuarantinedPayload) -> None: ...
    def quarantined_payloads(self, tenant_id: str,
                             limit: int = 100) -> list[QuarantinedPayload]: ...


@runtime_checkable
class SkillRepository(Protocol):
    """Skill identity, workspace listing and deterministic tag membership."""
    def upsert_skill(self, skill: Skill) -> None: ...
    def get_skill(self, skill_id: str) -> Skill | None: ...
    def delete_skill(self, skill_id: str) -> None: ...
    def skills_for_tenant(self, tenant_id: str) -> list[Skill]: ...
    def upsert_tag(self, tag_id: str, name: str) -> None: ...
    def tags_for_skill(self, skill_id: str) -> list[str]: ...
    def skills_by_tags(self, tags: set[str], tenant_id: str) -> list[Skill]: ...


@runtime_checkable
class RuleRepository(Protocol):
    """Durable rule content, placements and provenance without semantic policy."""
    def upsert_rule(self, rule: Rule) -> None: ...
    def create_rule_if_absent(self, rule: Rule) -> None: ...
    def get_rule(self, rule_id: str) -> Rule | None: ...
    def rules_for_skill(self, skill_id: str) -> list[Rule]: ...
    def skills_for_rule(self, rule_id: str) -> list[Skill]: ...
    def rules_for_tenant(self, tenant_id: str, limit: int = 500) -> list[Rule]: ...
    def rules_page(self, tenant_id: str, *, status: RuleStatus | None = None,
                   skill_id: str | None = None, query: str | None = None,
                   limit: int = 200, offset: int = 0) -> RulePage: ...
    def lineage(self, rule_id: str) -> list[Transaction]:
        """Return original and reinforcing contributions oldest first."""
        ...
    def rules_derived_from(self, transaction_ids: list[str]) -> dict[str, str]: ...
    def attach_edge(self, edge: Edge) -> None: ...
    def detach_edge(self, edge: Edge) -> None: ...


@runtime_checkable
class CustodyRepository(Protocol):
    """Source structure and artefact references; blob bytes use BlobStore."""
    def upsert_section(self, section: Section) -> None: ...
    def get_section(self, section_id: str) -> Section | None: ...
    def sections_for_skill(self, skill_id: str) -> list[Section]: ...
    def upsert_content_block(self, block: ContentBlock) -> None: ...
    def get_content_block(self, block_id: str) -> ContentBlock | None: ...
    def section_for_block(self, block_id: str) -> Section | None: ...
    def attach_block(self, block: ContentBlock, section_id: str) -> None: ...
    def blocks_for_section(self, section_id: str) -> list[ContentBlock]: ...
    def supersede_block(self, old_block_id: str, new_block: ContentBlock,
                        section_id: str, transaction_id: str | None = None) -> None: ...
    def attach_rule(self, rule: Rule, section_id: str,
                    order: int | None = None, group: str | None = None) -> None: ...
    def rules_for_section(self, section_id: str) -> list[Rule]: ...
    def rule_placements_for_section(self, section_id: str) -> list[RulePlacement]: ...
    def upsert_example(self, example: Example) -> None: ...
    def attach_example(self, example: Example) -> None: ...
    def examples_for_section(self, section_id: str) -> list[Example]: ...
    def examples_for_rule(self, rule_id: str) -> list[Example]: ...
    def examples_for_skill(self, skill_id: str) -> list[Example]: ...
    def upsert_artefact(self, artefact: Artefact, skill_id: str, path: str) -> None: ...
    def artefacts_for_skill(self, skill_id: str) -> list[tuple[Artefact, str]]: ...
    def observe_rule_in(self, rule_id: str, transaction_id: str, source_ref: str) -> None: ...


@runtime_checkable
class PublicationRepository(Protocol):
    """A tenant-owned ledger of exported files, with exact deletion scope."""
    def upsert_publication(self, publication: Publication) -> None: ...
    def get_publication(self, tenant_id: str, source_ref: str) -> Publication | None: ...
    def publications_for_skill(self, tenant_id: str, skill_id: str) -> list[Publication]: ...
    def delete_publications_for_skill(self, tenant_id: str, skill_id: str) -> None: ...
    def delete_publication(self, tenant_id: str, source_ref: str) -> None: ...


@runtime_checkable
class ReviewRepository(ReviewQueue, Protocol):
    """Pending items and durable, single-decision review history."""


@runtime_checkable
class HistoryRepository(Protocol):
    """Append snapshots and retain a bounded, tenant-scoped version history."""
    def append_skill_version(self, version: SkillVersion) -> None: ...
    def recent_skill_changes(self, tenant_id: str, limit: int = 8) -> list[SkillChange]: ...
    def skill_versions(self, tenant_id: str, skill_id: str, limit: int = 50,
                       before: datetime | None = None) -> list[SkillVersion]: ...
    def get_skill_version(self, version_id: str) -> SkillVersion | None: ...
    def latest_skill_version(self, tenant_id: str, skill_id: str) -> SkillVersion | None: ...
    def trim_skill_versions(self, tenant_id: str, skill_id: str, keep: int) -> int:
        """Keep the newest requested versions and always preserve the oldest."""
        ...


@runtime_checkable
class GraphReader(Protocol):
    """Fixed core graph reads; there is deliberately no arbitrary query method."""
    def get_skill(self, skill_id: str) -> Skill | None: ...
    def get_rule(self, rule_id: str) -> Rule | None: ...
    def get_transaction(self, transaction_id: str) -> Transaction | None: ...
    def skills_for_tenant(self, tenant_id: str) -> list[Skill]: ...
    def rules_for_skill(self, skill_id: str) -> list[Rule]: ...
    def sections_for_skill(self, skill_id: str) -> list[Section]: ...
    def blocks_for_section(self, section_id: str) -> list[ContentBlock]: ...
    def lineage(self, rule_id: str) -> list[Transaction]: ...
    def text_search(self, query: str, tenant_id: str,
                    limit: int = 20) -> list[tuple[str, float]]: ...


@runtime_checkable
class IngestionRepository(Protocol):
    """The persistence boundary needed before contribution disposition."""
    def get_transaction(self, transaction_id: str) -> Transaction | None: ...
    def upsert_transaction(self, transaction: Transaction) -> None: ...
    def record_quarantine(self, item: QuarantinedPayload) -> None: ...


@runtime_checkable
class HistoryCaptureRepository(HistoryRepository, Protocol):
    """History storage plus the content identity needed to capture a version."""
    def get_skill(self, skill_id: str) -> Skill | None: ...
    def tags_for_skill(self, skill_id: str) -> list[str]: ...
    def rules_for_skill(self, skill_id: str) -> list[Rule]: ...
    def skills_for_rule(self, rule_id: str) -> list[Skill]: ...


@runtime_checkable
class CatalogueRepository(Protocol):
    """Catalogue reads and fetch accounting, without changing skill content."""
    def skills_for_tenant(self, tenant_id: str) -> list[Skill]: ...
    def artefacts_for_skill(self, skill_id: str) -> list[tuple[Artefact, str]]: ...
    def get_publish_block(self, tenant_id: str) -> PublishBlock | None: ...
    def record_usage_event(self, event: UsageEvent) -> None: ...
