"""The ports the source feature is built against.

`SourceRepository` is what an adapter stores, `SourcePolicy` is what an edition decides
(who may act, what is safe, what may apply by itself) and `SourceService` is the
lifecycle the routes and the scheduler call.
"""
from datetime import datetime
from typing import Protocol, TYPE_CHECKING

from oms.domain.identity import SkillRef
from oms.sources.models import (
    ActionContext, ApplyRequest, AutomationRequest, Binding, BlockedAttempt, BulkApplyRequest,
    CheckRequest, CheckResult, CheckThrottle, CreateSourceRequest, DiscoveryRequest, DiscoveryResult,
    DurableEvent, Generations, InstallRequest, Lease, LinkRequest, LocalBatchRequest, LocalImportRequest, LocalState,
    LocalStream, ManifestEntry, MergePlan, Operation, OperationResult, OriginRef, Page, PartOwnership, ProjectionPart,
    RelocateSourceRequest, RemoveSourceRequest, RetargetRequest, SaveDraftRequest, ScheduleRequest, SnapshotRef, Source,
    SourceSnapshot, UndoRecord, UndoRequest, UndoStatus, UnlinkRequest, Update, UpdateRequest, UploadReplay,
)

if TYPE_CHECKING:
    from oms.ports.graph_store import GraphStore
    from oms.ports.review_queue import ReviewQueue


class SourceRepository(Protocol):
    """All writes participate in the caller's existing workflow transaction.

    Adapters enforce one open card per skill, one local stream per skill and
    one installed package per tenant/repository/path. Reads never infer scope
    from an opaque ID. Lists filter the supplied admitted skill scope before
    pagination. Snapshot insertion is immutable and duplicate IDs must agree.
    """
    def workspace_id(self, *, tenant_id: str, create: bool = True) -> str | None: ...
    def get_source(self, source_id: str, *, tenant_id: str) -> Source | None: ...
    def source_for_url(self, url: str, *, tenant_id: str) -> Source | None: ...
    def active_bindings(self, source_id: str, *, tenant_id: str) -> tuple[Binding, ...]: ...
    def active_bindings_for_tenant(self, *, tenant_id: str) -> tuple[Binding, ...]: ...
    def put_source(self, source: Source) -> None: ...
    def sources(self, *, tenant_id: str, skill_scope: tuple[SkillRef, ...],
                cursor: str | None = None, limit: int = 100) -> Page[Source]: ...
    def get_binding(self, skill: SkillRef) -> Binding | None: ...
    def put_binding(self, binding: Binding) -> None: ...
    def bindings(self, source_id: str, *, tenant_id: str,
                 skill_scope: tuple[SkillRef, ...], cursor: str | None = None,
                 limit: int = 100) -> Page[Binding]: ...
    def get_local_stream(self, skill: SkillRef) -> LocalStream | None: ...
    def put_local_stream(self, stream: LocalStream) -> None: ...
    def get_snapshot(self, ref: SnapshotRef) -> SourceSnapshot | None: ...
    def put_snapshot(self, snapshot: SourceSnapshot) -> None: ...
    def get_update(self, update_id: str, *, tenant_id: str) -> Update | None: ...
    def open_update(self, skill: SkillRef) -> Update | None: ...
    def put_update(self, update: Update) -> None: ...
    def get_generations(self, skill: SkillRef) -> Generations: ...
    def get_retirement(self, skill: SkillRef) -> Generations | None: ...
    def generations_for_tenant(self, *, tenant_id: str) -> tuple[Generations, ...]: ...
    def retire_skill(self, skill: SkillRef) -> tuple[Update, ...]: ...
    def ownership_for_skill(self, skill: SkillRef) -> tuple[PartOwnership, ...]: ...
    def put_ownership(self, ownership: PartOwnership) -> None: ...
    def clear_ownership(self, skill: SkillRef, part_id: str, *, entity_ids: tuple[str, ...] | None = None,
                        section_id: str | None = None) -> None: ...

    def lock_skills(self, skills: tuple[SkillRef, ...]) -> None:
        """Lock unique tenant-qualified keys in their canonical sorted order."""
        ...

    def compare_generations(self, expected: tuple[Generations, ...]) -> None:
        """Raise on any mismatch, including deleted/reinstalled skill fences."""
        ...

    def advance_generations(self, expected: Generations, replacement: Generations) -> None: ...
    def get_operation(self, operation_id: str, *, tenant_id: str) -> Operation | None: ...
    def operation_for_key(self, idempotency_key: str, *, tenant_id: str,
                          actor_id: str) -> Operation | None: ...

    def reserve_operation(self, operation: Operation) -> Operation:
        """Return matching replay or reserve; different digest reuse conflicts."""
        ...

    def put_operation(self, operation: Operation) -> None: ...
    def put_blocked_attempt(self, attempt: BlockedAttempt) -> None: ...
    def blocked_attempts(self, skill: SkillRef) -> tuple[BlockedAttempt, ...]: ...
    def clear_blocked_attempt(self, attempt_id: str, *, tenant_id: str) -> None: ...
    def get_undo(self, undo_id: str, *, tenant_id: str) -> UndoRecord | None: ...
    def put_undo(self, undo: UndoRecord) -> None: ...
    def claim_lease(self, lease: Lease, *, now: datetime) -> bool: ...
    def get_lease(self, resource_id: str, *, tenant_id: str) -> Lease | None: ...
    def release_lease(self, lease: Lease) -> None: ...
    def append_event(self, event: DurableEvent) -> None: ...
    def get_event(self, event_id: str, *, tenant_id: str) -> DurableEvent | None: ...
    def pending_events(self, *, tenant_id: str, now: datetime,
                       limit: int = 100) -> tuple[DurableEvent, ...]: ...
    def put_event(self, event: DurableEvent) -> None: ...
    def get_discovery(self, discovery_id: str, *, tenant_id: str,
                      actor_id: str, now: datetime) -> DiscoveryResult | None: ...
    def put_discovery(self, discovery: DiscoveryResult) -> None: ...
    def delete_discovery(self, discovery_id: str, *, tenant_id: str, actor_id: str) -> None: ...
    def claim_manual_check(self, throttle: CheckThrottle, *, now: datetime) -> bool: ...
    def get_manual_check(self, source_id: str, *, tenant_id: str) -> CheckThrottle | None: ...
    def suppress_candidate(self, origin: OriginRef, revision: str) -> None: ...
    def candidate_suppressed(self, origin: OriginRef, revision: str) -> bool: ...


class SourcePolicy(Protocol):
    def admit(self, action: str, context: ActionContext,
              skill_refs: tuple[SkillRef, ...]) -> None:
        """Revalidate current authority, including on replay and at commit."""
        ...

    def admit_install(self, context: ActionContext, request: InstallRequest) -> None:
        """Validate current rights for each requested domain before its skill exists."""
        ...

    def admit_profile(self, context: ActionContext, profile_id: str | None) -> None:
        """Authorise personal discovery and explicit package/ref changes, not bound checks."""
        ...

    def admit_local(self, context: ActionContext, request: LocalImportRequest) -> None:
        """Validate explicit local target and any new domain without inferring origin from its filename."""
        ...

    def admit_operation(self, context: ActionContext, operation: Operation, graph: "GraphStore") -> None:
        """Revalidate receipt scope, including admitted targets that were never created."""
        ...

    def revision(self, context: ActionContext, graph: "GraphStore", reviews: "ReviewQueue",
                 skill_refs: tuple[SkillRef, ...]) -> str:
        """Fingerprint mutable safety policy through the supplied transaction-bound readers."""
        ...

    def screen(self, snapshot: SourceSnapshot, local: LocalState) -> CheckResult: ...

    def screen_resolved(self, snapshot: SourceSnapshot, local: LocalState,
                        writes: tuple[ProjectionPart, ...], *,
                        manifest: tuple[ManifestEntry, ...] | None = None) -> CheckResult:
        """Screen actual selected writes while retaining the original upstream evidence."""
        ...

    def automatic_eligibility(self, plan: MergePlan, binding: Binding) -> CheckResult: ...


class SourceService(Protocol):
    """Facade inputs are typed; only edition admission creates ActionContext."""
    def discover(self, context: ActionContext, request: DiscoveryRequest, *,
                 idempotency_key: str) -> DiscoveryResult: ...
    def create_source(self, context: ActionContext, request: CreateSourceRequest, *,
                      idempotency_key: str) -> OperationResult: ...
    def install(self, context: ActionContext, request: InstallRequest, *,
                idempotency_key: str) -> OperationResult: ...
    def check(self, context: ActionContext, request: CheckRequest, *,
              idempotency_key: str) -> OperationResult: ...
    def link(self, context: ActionContext, request: LinkRequest, *,
             idempotency_key: str) -> OperationResult: ...
    def relink(self, context: ActionContext, request: LinkRequest, *,
               idempotency_key: str) -> OperationResult: ...
    def retarget(self, context: ActionContext, request: RetargetRequest, *,
                 idempotency_key: str) -> OperationResult: ...
    def save_draft(self, context: ActionContext, request: SaveDraftRequest, *,
                   idempotency_key: str) -> OperationResult: ...
    def recheck(self, context: ActionContext, request: UpdateRequest, *,
                idempotency_key: str) -> OperationResult: ...
    def apply(self, context: ActionContext, request: ApplyRequest, *,
              idempotency_key: str) -> OperationResult: ...
    def skip(self, context: ActionContext, request: UpdateRequest, *,
             idempotency_key: str) -> OperationResult: ...
    def adopt(self, context: ActionContext, request: UpdateRequest, *,
              idempotency_key: str) -> OperationResult: ...
    def undo(self, context: ActionContext, request: UndoRequest, *,
             idempotency_key: str) -> OperationResult: ...
    def undo_status(self, context: ActionContext, undo_id: str) -> UndoStatus: ...
    def bulk_apply(self, context: ActionContext, request: BulkApplyRequest, *,
                   idempotency_key: str) -> OperationResult: ...
    def unlink(self, context: ActionContext, request: UnlinkRequest, *,
               idempotency_key: str) -> OperationResult: ...
    def remove_source(self, context: ActionContext, request: RemoveSourceRequest, *,
                      idempotency_key: str) -> OperationResult: ...
    def relocate_source(self, context: ActionContext, request: RelocateSourceRequest, *,
                        idempotency_key: str) -> OperationResult: ...
    def configure_automation(self, context: ActionContext, request: AutomationRequest, *,
                             idempotency_key: str) -> OperationResult: ...
    def configure_schedule(self, context: ActionContext, request: ScheduleRequest, *,
                           idempotency_key: str) -> OperationResult: ...
    def submit_local(self, context: ActionContext, request: LocalImportRequest, *,
                     idempotency_key: str) -> OperationResult: ...
    def submit_local_batch(self, context: ActionContext, request: LocalBatchRequest, *,
                           idempotency_key: str, upload_replay: UploadReplay | None = None) -> OperationResult: ...
